"""schema_alignment

Revision ID: 0dd79792bbae
Revises: d0f5b8c4e236
Create Date: 2026-08-17 16:28:07.706014+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import context, op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd79792bbae'
down_revision: str | Sequence[str] | None = 'd0f5b8c4e236'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _require_destructive_downgrade() -> None:
    """Require an explicit opt-in before applying downgrade operations."""
    arguments = context.get_x_argument(as_dictionary=True)
    if arguments.get("allow-destructive", "").casefold() != "true":
        raise RuntimeError(
            "Destructive downgrade blocked; rerun with "
            "'-x allow-destructive=true' after verifying the database target"
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_registry', 'status_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('agent_registry', 'force_closed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_sessions', 'approval_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cmdb_assets', 'vendor',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cmdb_assets', 'credential_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cmdb_assets', 'credential_username',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_command_policies', 'note',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_command_policies', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('hitl_execution_results_proposal_id_key'), 'hitl_execution_results', type_='unique')
    op.drop_index(op.f('ix_hitl_execution_results_proposal_id'), table_name='hitl_execution_results')
    op.create_index(op.f('ix_hitl_execution_results_proposal_id'), 'hitl_execution_results', ['proposal_id'], unique=True)
    op.alter_column('knowledge_documents', 'suggestion_reason',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_knowledge_documents_suggested_category_id'), table_name='knowledge_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    _require_destructive_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_knowledge_documents_suggested_category_id'), 'knowledge_documents', ['suggested_category_id'], unique=False)
    op.alter_column('knowledge_documents', 'suggestion_reason',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.drop_index(op.f('ix_hitl_execution_results_proposal_id'), table_name='hitl_execution_results')
    op.create_index(op.f('ix_hitl_execution_results_proposal_id'), 'hitl_execution_results', ['proposal_id'], unique=False)
    op.create_unique_constraint(op.f('hitl_execution_results_proposal_id_key'), 'hitl_execution_results', ['proposal_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('device_command_policies', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('device_command_policies', 'note',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('cmdb_assets', 'credential_username',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('cmdb_assets', 'credential_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'none'::character varying"),
               existing_nullable=False)
    op.alter_column('cmdb_assets', 'vendor',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'approval_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ask'::character varying"),
               existing_nullable=False)
    op.alter_column('agent_registry', 'force_closed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('agent_registry', 'status_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
